[package]
name = "arq-io-async"
version = "0.0.3"
authors = [
  "Thomas Ivesdal-Tronstad <>",
]
license = "MIT OR Apache-2.0"
description = "Asynchronous implementation of ARQ in Rust."
repository = "https://github.com/thives/arq-io-async.rs"
keywords = ["arq", "reliable", "retrans", "io", "async"]
edition = "2024"
rust-version = "1.87"

[features]
default = ["serde"]
serde = ["dep:serde"]
defmt = ["dep:defmt"]

[dependencies]
defmt = { version = "1", optional = true }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }
crc = { version = "3.4" }

[dev-dependencies]
embassy-time = { version = "0.5", features = ["std", "generic-queue-8"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition"]
